### ISSUE TITLE
Home page is not accessible 

### ISSUE THREAD

**Issue by zengbing15** [cryptape/cyton-ios#278]
![image](https://user-images.githubusercontent.com/40650475/56723871-6afbc000-677c-11e9-9d82-537aa57bbe81.png)

**Comment by zengbing15** [comment]
Cyton iOS does not have this bug.

**Comment by zengbing15** [comment]
actually, Cyton iOS and cita-sdk-js both have bugs.

**Comment by xiaoluSF** [comment]
[279](https://github.com/cryptape/cyton-ios/pull/279)
